name: Building and deployment
on : [push,pull_request]
# on:
#   push:
#     branches:
#      - "main"
#   pull_request:
#     branches:
#      - "main"
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repository
        uses: actions/checkout@v3
      - name: print step
        run: echo "yellow"
