name: Building and deployment
on : [push,pull_request]
# on:
#   push:
#     branches:
#      - "main"
#   pull_request:
#     branches:
#      - "main"
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repository
        uses: actions/checkout@v3
      - name: install python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt

